name: CI Pipeline

on:
  push:
    branches: main
    tags:
      - '*'
  pull_request:

env:
  UV_CACHE_DIR: .cache/uv
  PIP_CACHE_DIR: .cache/pip

jobs:
  ruff-format:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: "3.12.7"
      - name: Install Ruff
        run: |
          pip install uv
          uv sync --no-dev --frozen
          uv add ruff
      - name: Run Ruff Format
        run: uv run ruff format --check --diff .

  ruff-check:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: "3.12.7"
      - name: Install Ruff
        run: |
          pip install uv
          uv sync --no-dev --frozen
          uv add ruff
      - name: Run Ruff Check
        run: uv run ruff check .

  mypy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: "3.12.7"
      - name: Install uv and dependencies
        run: |
          pip install uv
          uv sync --no-dev --frozen
          uv add mypy
      - name: Run Mypy
        run: uv run mypy .

  test:
    runs-on: self-hosted
    needs: [ruff-format, ruff-check, mypy]
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: "3.12.7"
      - name: Install uv and dependencies
        run: |
          pip install uv
          uv sync --frozen
      - name: Run tests
        run: |
          uv run coverage run -m pytest
          uv run coverage xml
      - name: Upload coverage
        uses: actions/upload-artifact@v7
        with:
          name: coverage-report
          path: coverage.xml
